require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# Override Firebase SDK Version
$FirebaseSDKVersion = '7.6.0'

target 'ReactNativeSwitchPages' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  target 'ReactNativeSwitchPagesTests' do
    inherit! :complete
    # Pods for testing
  end

  #Enables Flipper.
  
   #Note that if you have use_frameworks! enabled, Flipper will not work and
   #you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
   #flipper_post_install(installer)
  #end
end

target 'ReactNativeSwitchPages-tvOS' do
  # Pods for ReactNativeSwitchPages-tvOS

  target 'ReactNativeSwitchPages-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Firestore'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

 # React Native Maps dependencies
 rn_maps_path = '../node_modules/react-native-maps'
 pod 'react-native-google-maps', :path => rn_maps_path
 pod 'GoogleMaps'
 pod 'Google-Maps-iOS-Utils'